server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iamsubho76/ItemSharing/tree/master/ItemSharing.GitHubRepo/src/main/resources
          username: iamsubho76
          password: '{cipher}48d972cc39eac26dee8deb50ebd8a06de374d1f23d155039cf45f50a2ed776a6bdceb6a9dfc81e07eee58eb82785352c'
          search-paths: userservice, itemservice
        encrypt:
          enabled: false